### ISSUE TITLE
Use DPDT relay to comply with safety standards

### ISSUE THREAD

**Issue by phckopper** [balena-io-hardware/autokit-relay-3d#2]
> @rcooke-warwick, @phckopper 
> For production will be good to use a DPDT relay that can cut off both AC phases (L&N). In this case use terminals with pitch 7.62mm to be compatible with safety standards.

_Originally posted by @zisis00 in https://github.com/balena-io-hardware/autokit-relay-3d/issues/1#issuecomment-1209229712_

**Comment by rcooke-warwick** [comment]
recommended to use this one 

https://www.amazon.de/-/en/ARCELI-SRD-05VDC-SL-C-Module-Control-Intelligent/dp/B07JL4YB8R/ref=sr_1_2?crid=13PWMB4QVQP8Y&keywords=ARCELI+SRD-05VDC-SL-C&qid=1660926567&sprefix=arceli+srd-05vdc-sl-c%2Caps%2C110&sr=8-2
