### ISSUE TITLE
Use power entry modules for PCB

### ISSUE THREAD

**Issue by phckopper** [balena-io-hardware/autokit-relay-3d#3]
> Also, you can use power entry modules for pcb to avoid the cables and the friction during assembly and sourcing, for example:https://www.amazon.com/Power-Entry-Modules-Mount-piece/dp/B00M1K8216. In this case the pcb should be larger and re-design the case to match the height. I think it worth as the total cost and the complexity are less.

_Originally posted by @zisis00 in https://github.com/balena-io-hardware/autokit-relay-3d/issues/1#issuecomment-1209229712_

**Comment by rcooke-warwick** [comment]
as we are not using a custom relay PCB, I think we can close this issue for now
